### PR TITLE
Basic Implementation of Linear Search

### PR DESCRIPTION
**Pull request by YuZaGa**

### CODE REVIEW

**Review by rishabh-live — CHANGES_REQUESTED** [review]
Write comments so that it is beginner friendly

**Review by rishabh-live — CHANGES_REQUESTED** [review]
Use Variable Name more specific to usecases

**Comment by YuZaGa** [comment]
> Write comments so that it is beginner friendly

Done

**Review by rishabh-live — APPROVED** [review]
- [x] Accepted

**Pull request merged**
